apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dynmap
  namespace: minecraft
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: dynmap.hexagonlabs.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crafty
                port:
                  number: 8123
