apiVersion: apps/v1
kind: Deployment
metadata:
  name: crafty
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crafty
  template:
    metadata:
      labels:
        app: crafty
    spec:
      containers:
        - name: crafty
          image: registry.gitlab.com/crafty-controller/crafty-4:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "Etc/UTC"
          ports:
            - name: crafty-ui
              containerPort: 8443
            - name: dynmap
              containerPort: 8123
            - name: mc-range
              containerPort: 25500
            - name: mc-range-2
              containerPort: 25600
          volumeMounts:
            - name: crafty-servers
              mountPath: /crafty/servers
            - name: crafty-logs
              mountPath: /crafty/logs
            - name: crafty-backups
              mountPath: /crafty/backups
            - name: crafty-config
              mountPath: /crafty/app/config
            - name: crafty-import
              mountPath: /crafty/import
      volumes:
        - name: crafty-servers
          persistentVolumeClaim:
            claimName: crafty-servers
        - name: crafty-logs
          persistentVolumeClaim:
            claimName: crafty-logs
        - name: crafty-backups
          persistentVolumeClaim:
            claimName: crafty-backups
        - name: crafty-config
          persistentVolumeClaim:
            claimName: crafty-config
        - name: crafty-import
          persistentVolumeClaim:
            claimName: crafty-import
