apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: crafty-tcp
  namespace: minecraft
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`crafty.hexagonlabs.cloud`)
      services:
        - name: crafty
          port: 8443
