apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      containers:
        - name: velocity
          image: itzg/mc-proxy:latest
          imagePullPolicy: Always
          env:
            - name: TYPE
              value: "VELOCITY"
            - name: EULA
              value: "TRUE"
            - name: OVERRIDE
              value: "false"
          ports:
            - name: minecraft
              containerPort: 25565
            - name: query
              containerPort: 25575
          volumeMounts:
            - name: config
              mountPath: /config/velocity.toml
              subPath: velocity.toml
      volumes:
        - name: config
          configMap:
            name: velocity-config
