apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      containers:
      - name: velocity
        image: eclipse-temurin:21-jdk
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Downloading Velocity..."
            curl -o velocity.jar https://api.papermc.io/v2/projects/velocity/versions/3.4.0-SNAPSHOT/builds/557/downloads/velocity-3.4.0-SNAPSHOT-557.jar
            echo "Starting Velocity..."
            java -Xms512m -Xmx512m -jar velocity.jar
        ports:
        - containerPort: 25565
          name: minecraft
        - containerPort: 25575
          name: query
        volumeMounts:
        - name: velocity-config
          mountPath: /config/velocity.toml
          subPath: velocity.toml
        - name: velocity-secret
          mountPath: /server/forwarding.secret
          subPath: forwarding.secret
      volumes:
      - name: velocity-config
        configMap:
          name: velocity-config
      - name: velocity-secret
        emptyDir: {}
