apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft

resources:
  - namespace.yaml

  # Crafty (controller + storage)
  - crafty/pvc.yaml
  - crafty/deployment.yaml
  - crafty/service.yaml
  - crafty/fabric-service.yaml
  - crafty/ingress.yaml
  - crafty/ingress-tcp.yaml

  # Velocity (public proxy)
  - velocity/configmap.yaml
  - velocity/deployment.yaml
  - velocity/service-nodeport.yaml

  # Dynmap (internal map via Traefik)
  - dynmap/ingress.yaml
